# Generated by Django 4.1 on 2024-05-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_remove_listing_bid_amount_check_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="bid_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
