# Generated by Django 4.1 on 2024-05-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_alter_listing_bid_amount"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="listing",
            name="bid_amount_check",
        ),
        migrations.AlterField(
            model_name="listing",
            name="bid_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("bid_amount", 0),
                    ("bid_amount__gt", models.F("start_price")),
                    _connector="OR",
                ),
                name="bid_amount_check",
                violation_error_message="Bid amount must be greater than the start price.",
            ),
        ),
    ]
