# Generated by Django 4.1 on 2024-06-21 23:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_notification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
