# Generated by Django 4.1 on 2024-06-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_delete_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="image",
            field=models.ImageField(blank=True, upload_to="uploads/listing/"),
        ),
    ]
