# Generated by Django 4.1 on 2024-06-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0010_listing_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/listing/"
            ),
        ),
    ]
